name: liesel-install-jss
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip
  - pygraphviz
  - python
  - quarto
  - r-base
  - r-ggplot2
  - r-knitr
  - r-mgcv
  - r-remotes
  - r-reticulate
  - r-rmarkdown
  - pip:
    - liesel<0.3
